### ISSUE TITLE
Creación del Informe 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#1]
Se establecerá la base del informe

**Comment by SebastianOsorio20** [comment]
Se creo el archivo Informe.md , tomando como base nuestro informe del TP donde se muestra el mapa , los nodos ; pero ahora usando Markdown para un mejor entendimiento

**Comment by MarlonLLaguento** [comment]
Se tomará como base el informe realizado en el TP, ya que contiene la información de las intersecciones de las calles. Seguidamente, se agregarán nuevos detalles del proyecto como las distancias entre los cruces.

**Comment by Tyrone-J** [comment]
El informe que presentamos para esta coaction fue un reciclado del trabajo parcial pero con la diferencia de que traspasamos el word que teníamos a el lenguaje html para que se pueda apreciar de manera mas detallada en el github. Este informe nos da un resumen del enunciado del trabajo junto a nuestra propuesta de solución, mostrando la calle a la cual decidimos hacer los 1500 nodos y explicando el motivo de nuestra decision. Igualmente este informe no esta 100% culminado así que se ira actualizando mediante avancemos con las entregas del trabajo final con el fin de entregar un buen informe.
