### ISSUE TITLE
Actividades finales de la aplicación, corrección de errores y puesta a punto.

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#10]
Testing

**Comment by SebastianOsorio20** [comment]
Se finalizo el proyecto corrigiendo algunos errores que quedaban

**Comment by Tyrone-J** [comment]
Se corrigieron diversos errores que habían en los arreglos como serian el caso de nodos repetidos o nodos con valores de mas.

**Comment by MarlonLLaguento** [comment]
Se corrigieron errores en las listas de adyacencia y en los archivos de JavaScript.
