### ISSUE TITLE
Finalización de las conclusiones del informe

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#11]
Termino del informe

**Comment by SebastianOsorio20** [comment]
Se realizo el informe del proyecto conforme a lo planteado

**Comment by Tyrone-J** [comment]
Se elaboro el informe, explicando detalladamente todo lo que se elaboro para hacer el trabajo final.

**Comment by MarlonLLaguento** [comment]
Se terminó el informe con la concluyendo que el algoritmos de Dijkstra da el mejor recorrido pero con un tiempo de ejecución mayor en caso los nodos aumentaran en número.
