### ISSUE TITLE
Elaboración de un video

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#12]
De mínimo 3 minutos y máximo 8, el cual deberá ser subido a una plataforma online compartido por URL. Al repositorio se deberá agregar un archivo de Markdown llamado video.md con el link a dicho video

**Comment by SebastianOsorio20** [comment]
se elaboro el video para el proyecto

**Comment by Tyrone-J** [comment]
Se realizo el video explicando todo lo realizado en el trabajo final

**Comment by MarlonLLaguento** [comment]
Realizamos el video explicando el funcionamiento del programa y la implementación de la interfaz gráfica.
