### ISSUE TITLE
Pasar el informe a Markdown

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#2]
Se aprenderá los comandos de md

**Comment by SebastianOsorio20** [comment]
Se logro pasar el informe del TP a Markdown y se subió al github

**Comment by MarlonLLaguento** [comment]
Se usó el formato Markdown para organizar el informe, además cuando se ingrese nueva información será guardad como comits que será registrado en Github.

**Comment by Tyrone-J** [comment]
mondongo 😎
