### ISSUE TITLE
Pasar el código del TP a GitHub 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#3]
Traspasar el código de nuestros nodos

**Comment by SebastianOsorio20** [comment]
Se subió el código de los nodos  de nuestro TP, en el Python con algunos inconvenientes pero se soluciono todo al final

**Comment by Tyrone-J** [comment]
Este punto fue algo sencillo ya que teníamos casi todo el código terminado en el lenguaje de python, solo tuvimos que arreglar unos cuantos detalles para corroborar que el código nos de un resultado satisfactorio.

**Comment by MarlonLLaguento** [comment]
Se tenía el código terminado, así que solo se tubo que crear un archivo en nuestro repositorio para pasar el programa a Github.
