### ISSUE TITLE
Agregar información adicional al grafo

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#4]
coordenadas de intersecciones
información de tráfico por hora de calles o segmentos de calle

**Comment by MarlonLLaguento** [comment]
Se agregó una condición mas que es el tiempo para hallar el trafico en ciertas avenidas.

**Comment by SebastianOsorio20** [comment]
Se detallo en el informe las calles e intersecciones del mapa , además que se eligió 3 turnos de trafico siendo trafico bajo , trafico medio y trafico alto

**Comment by Tyrone-J** [comment]
Decidimos agregar la información del tiempo que se demora de un nodo a otro, siendo este tiempo el peso las aristas de los nodos. Para esto hicimos el horario de 3 tipos de aristas que dependen de la hora que elija el usuario,
