### ISSUE TITLE
Actividades de implementación de algoritmo de cálculo de peso de arista

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#5]
En función de su longitud y factor de tráfico calculado.

**Comment by MarlonLLaguento** [comment]
Utilizamos la función perlin noice,  la hora del día y la distancia para poder hallar el peso de cada arista. Es decir, obtenemos el tiempo que demora un auto en pasar por cierta calle.

**Comment by SebastianOsorio20** [comment]
Usando perlin noise se le altero el factor del peso del grafo , teniendo un ruido mas suave al crearlo y siendo trafico bajo , medio y alto

**Comment by Tyrone-J** [comment]
Para hallar el peso de las aristas utilizamos el algoritmo de Perlin Noise. Primero utilizamos el perlin noise para hallar el tiempo de la arista en trafico medio, variando este entre 7 a 15. Luego al resultado del trafico medio le restamos para el trafico bajo con Perlin noise entre 1 a 4. Y para el trafico mas Alto le sumamos al trafico medio con perlin Noise entre 1 a 6.
