### ISSUE TITLE
Actividades de implementación de algoritmos para actualizar pesos de aristas

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#6]
En función a la hora del día.

**Comment by MarlonLLaguento** [comment]
Gracias al algoritmo para hallar los pesos de las aristas, obtuvimos nuevos grafos dependiendo del tiempo en la que se hace la consulta. Se tomó el grafo principal y se le asignó los valor correspondientes de los nuevos pesos.

**Comment by SebastianOsorio20** [comment]
Al tener el grafo con perlin noise se opto por tener 3 tiempos de trafico teniendo un ruido suave , eligiéndose en el menú principal

**Comment by Tyrone-J** [comment]
Para escoger el tiempo de trafico decidimos hacer un menu para pedir el tiempo en el cual escoge el usuario, y depende del tiempo variada el tamaño del peso de la arista.
