### ISSUE TITLE
Actividades de implementación de algoritmos para calcular la ruta más corta

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#7]
y 2 rutas alternativas.

**Comment by MarlonLLaguento** [comment]
Se hizo uso del algoritmo de Jhonson para hallar la ruta mas corta entre los nodos. Así pues, se podrá recomendar los caminos con menor tiempo de recorrido.

**Comment by Tyrone-J** [comment]
Se utilizo el algoritmo Jhonson enseñado en clase para poder calcular las ruta más corta de un nodo a otro. Tuvimos que hacer varias pruebas con otros algoritmos pero al final la que mas nos convenció fue el de Jhonson.

**Comment by SebastianOsorio20** [comment]
Se logro la implementación  algoritmo de Jonhson y BellmanFord para conseguir la ruta mas corta de nuestros grafos ,ya que para el grupo eran los algoritmos mas óptimos para resolver el hito 3
