### ISSUE TITLE
Actividades de implementación de interfaz de usuario

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#8]
Diseño de interfaz

**Comment by SebastianOsorio20** [comment]
Se logro elaborar un menú donde el usuario escoge el horario del día y dependiendo eso se selecciona el grafo con el tráfico respectivo

**Comment by MarlonLLaguento** [comment]
Se implementó los servicios de conda para la creación de la UI implementado en una página web.

**Comment by Tyrone-J** [comment]
Se logro un menu satisfactorio que muestra los horarios de los traficos y nos da los paths según la hora ingresada exitosamente
