### ISSUE TITLE
Actividades de implementación de visualización del mapa y las rutas

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/TF-201713107-20201b055-202017267#9]
Usando su implementación de grafo y algoritmos

**Comment by SebastianOsorio20** [comment]
Falta arreglar algunos errores en la parte de visualización de las rutas mas cortas en el mapa pero el programa funciona correctamente

**Comment by MarlonLLaguento** [comment]
Se logró parametrizar las coordenadas para la graficación del grafo en un sitio web, así se podrá tener una mejor visualización del mapa. Sin embargo, se mejorará aun mas el mapa.

**Comment by Tyrone-J** [comment]
Se logro generar el mapa pero aun se haran mejoras para la entrega de la version final.
